apiVersion: v1
kind: PersistentVolume
metadata:
  name: dig-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: do--block-storage
