apiVersion: apps/v1
kind: Deployment # kind specifies the kind of service we are creating within k8s
metadata:
  name: nginx-deployment # name of the deployemnt
  namespace: default # name space within which the deployment runs
spec:
  replicas: 2
  selector: # this is used to identify which pods belong to this deployment
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx # labels for a pod
    spec:
      containers: # list of containers that run within a pod
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
