kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30005
        hostPort: 30005
  - role: worker
    extraPortMappings:
      - containerPort: 30005
        hostPort: 30006
  - role: worker
    extraPortMappings:
      - containerPort: 30005
        hostPort: 30007
