apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cpu-app
  template:
    metadata:
      labels:
        app: cpu-app
    spec:
      containers:
        - name: cpu-app
          image: 100xdevs/week-28:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "1000m"
            limits:
              cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: cpu-deployment-service
spec:
  type: LoadBalancer
  selector:
    app: cpu-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
