apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  .env: VVNFUk5BTUU9InZpY3RvcjE0MiIKUEFTU1dPUkQ9ImFtYnJvc2UxNG1qdmljJCI=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-volume-ecom-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-backend
  template:
    metadata:
      labels:
        app: ecom-backend
    spec:
      containers:
        - name: dotfile-test-container
          image: victorchrollo14/env-backend:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: env-file
              readOnly: true
              mountPath: "/usr/src/app/env"
      volumes:
        - name: env-file
          secret:
            secretName: dotfile-secret

---
apiVersion: v1
kind: Service
metadata:
  name: ecom-backend-service
spec:
  type: NodePort
  selector:
    app: ecom-backend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
